### ISSUE TITLE
Will this work in multiplayer servers/realms? and can you add a setting so that when i break a crop it only replants that singular crop on the singular farmland and not spreaded? Also can you add a feature that will not let you break immature crops? 

### ISSUE THREAD

**Issue by FastPhase** [Tr4nter/auto-plant-crop#8]

**Comment by Tr4nter** [comment]
1.Will this work in multiplayer servers/realms?
Yes
2.can you add a setting so that when i break a crop it only replants that singular crop on the singular farmland and not spreaded?
/plantMultiple 
3.can you add a feature that will not let you break immature crops? 
/plantDespiteAge

make sure you check the mod's modrinth description page before askling questions

**Comment by Tr4nter** [comment]
https://modrinth.com/mod/auto-plant-crops/version/1.1.4
added prevent breaking immature crops
